modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/corpse/issues"
[[mods]]
modId = "corpse"
version = "${mod_version}"
displayName = "Corpse"
updateJSONURL = "https://update.maxhenkel.de/forge/corpse"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/corpse"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''
This mod brings a corpse into the game.
It will spawn upon your death containing all items that you had in your inventory.
'''
[[dependencies.corpse]]
modId = "forge"
mandatory = true
versionRange = "${forge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.corpse]]
modId = "jade"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"